const { getTemplatesByFrequency, getTemplate } = require('./pmTemplates');
const { LANES } = require('../config/lanes');

/**
 * PM Scheduler - Auto-generates preventative maintenance tasks
 */

/**
 * Generate PM tasks for today based on equipment type and config
 */
async function generatePMTasksForToday(stateManager, config) {
  const equipmentType = config.equipmentType || 'generic';
  const today = new Date();
  today.setHours(6, 0, 0, 0); // Default start time 6:00 AM

  const tasks = [];

  // Get daily templates
  const dailyTemplates = getTemplatesByFrequency('daily', equipmentType);
  for (const template of dailyTemplates) {
    if (template.perLane) {
      // Create task for each lane
      for (const lane of LANES) {
        const task = createTaskFromTemplate(template, lane, today);
        tasks.push(task);
      }
    } else {
      // Create single facility-wide task
      const task = createTaskFromTemplate(template, null, today);
      tasks.push(task);
    }
  }

  // Check if it's Monday (weekly tasks)
  if (today.getDay() === 1 && config.autoGenerateWeekly !== false) {
    const weeklyTemplates = getTemplatesByFrequency('weekly', equipmentType);
    const weeklyTime = new Date(today);
    weeklyTime.setHours(7, 0, 0, 0); // Weekly tasks start at 7:00 AM

    for (const template of weeklyTemplates) {
      if (template.perLane) {
        for (const lane of LANES) {
          const task = createTaskFromTemplate(template, lane, weeklyTime);
          tasks.push(task);
        }
      } else {
        const task = createTaskFromTemplate(template, null, weeklyTime);
        tasks.push(task);
      }
    }
  }

  // Check if it's first day of month (monthly tasks)
  if (today.getDate() === 1 && config.autoGenerateMonthly !== false) {
    const monthlyTemplates = getTemplatesByFrequency('monthly', equipmentType);
    const monthlyTime = new Date(today);
    monthlyTime.setHours(8, 0, 0, 0); // Monthly tasks start at 8:00 AM

    for (const template of monthlyTemplates) {
      if (template.perLane) {
        for (const lane of LANES) {
          const task = createTaskFromTemplate(template, lane, monthlyTime);
          tasks.push(task);
        }
      } else {
        const task = createTaskFromTemplate(template, null, monthlyTime);
        tasks.push(task);
      }
    }
  }

  // Add tasks to state
  for (const task of tasks) {
    await stateManager.addMaintenanceTask(task);
  }

  console.log(`[PM Scheduler] Generated ${tasks.length} PM tasks for ${equipmentType}`);
  return tasks;
}

/**
 * Create a maintenance task from a PM template
 */
function createTaskFromTemplate(template, lane, scheduledTime) {
  return {
    type: 'preventative',
    title: lane ? `${template.title} - Lane ${lane}` : template.title,
    description: template.description,
    lane: lane,
    priority: template.priority || 'medium',
    assignedTo: '',
    scheduledFor: scheduledTime.getTime(),
    estimatedDuration: template.estimatedDuration,
    recurringPattern: null, // PM tasks don't auto-recur, they're generated by scheduler
    status: 'pending',
    pmTemplate: template.id,
    checklist: template.checklistItems,
    manualReference: template.manualReference
  };
}

/**
 * Check if PM tasks need to be generated for today
 */
async function checkAndGeneratePMTasks(stateManager) {
  try {
    // Get PM config
    const config = await stateManager.getPMConfig();
    if (!config || !config.enabled) {
      console.log('[PM Scheduler] PM module disabled, skipping task generation');
      return;
    }

    // Check if tasks already exist for today
    const today = new Date();
    const todayStr = today.toISOString().split('T')[0];
    const todayStart = new Date(today);
    todayStart.setHours(0, 0, 0, 0);
    const todayEnd = new Date(today);
    todayEnd.setHours(23, 59, 59, 999);

    const allTasks = await stateManager.getMaintenanceTasks();
    const todayPMTasks = allTasks.filter(task =>
      task.pmTemplate &&
      task.scheduledFor >= todayStart.getTime() &&
      task.scheduledFor <= todayEnd.getTime()
    );

    if (todayPMTasks.length > 0) {
      console.log(`[PM Scheduler] ${todayPMTasks.length} PM tasks already exist for today`);
      return;
    }

    // Generate tasks
    await generatePMTasksForToday(stateManager, config);

    // Update last generated timestamp
    config.lastGenerated = Date.now();
    await stateManager.setPMConfig(config);

  } catch (error) {
    console.error('[PM Scheduler] Error generating PM tasks:', error);
  }
}

module.exports = {
  generatePMTasksForToday,
  checkAndGeneratePMTasks,
  createTaskFromTemplate
};
