apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lunar-lanes.fullname" . }}-secrets
  labels:
    {{- include "lunar-lanes.labels" . | nindent 4 }}
type: Opaque
stringData:
  GCAL_API_KEY: {{ .Values.backend.googleCalendar.apiKey | default "" | quote }}
  GCAL_CALENDAR_ID: {{ .Values.backend.googleCalendar.calendarId | default "" | quote }}
  {{- if .Values.backend.googleCalendar.serviceAccountJson }}
  GCAL_SERVICE_ACCOUNT_JSON: {{ .Values.backend.googleCalendar.serviceAccountJson | quote }}
  {{- end }}
